### ISSUE TITLE
New project checklist

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/wp4-aud_manager#2]
Please make sure all the items are addressed
- [x] Does the project have a `README.md` ?
    - [ ] Does the readme provide build and run instruction?
    - [ ] Does the readme explain what the code is supposed to do?
- [ ] Does the project have a `LICENSE` file?
    - If possible use either [MIT](https://spdx.org/licenses/MIT) or other compatible licenses.
- [ ] Does the project have a [GitHub Action](https://github.com/features/actions)?
    - [ ] Does it upload the code coverage somewhere?
    - [ ] Does it manage the release of the code? (Continuous Delivery)
- [ ] Does it have a DockerFile or does it need it?
